### PR TITLE
Adds Quiet, Skip, and Method Flags plus commit checks

### PR DESCRIPTION
**Pull request by evans**
This PR adds the quiet flag to suppress the spinner output and optional warnings. It also adds flags to skip images and duplicate pages. It also enables the pages to be fetched with a get request in [blc](https://github.com/stevenvachon/broken-link-checker#optionsrequestmethod).

It also adds in a standard fix precommit and standard check prepush.

@adamisntdead You should also be aware of [semver](https://semver.org/#spec-item-8). When you make breaking changes, such as modifying the process exit code, you should make sure to do a major version bump. Depending on how people setup their npm dependencies, with patch or minor versions, their setup can break without any modifications, which can be frustrating. This PR re-enables the exit code setting to 1 when any of the checks fail. Continuous Integration uses this code to determine if a script fail, so without this poke-site would only be useful for manual checks.

Thanks for putting together the library!

### CODE REVIEW

**Comment by adamisntdead** [comment]
Thanks for the PR!

I havn't been that strict with the versioning so far, as the library was mainly for the CLI.

I am going to refactor this in the next few days to use promises, remove all of the logging and the process.exits (I will put them on the CLI side)

Thanks for your support!

**Comment by adamisntdead** [comment]
I will publish once that's finished btw

**Comment by evans** [comment]
Awesome! Look forward to it.

I think it's important to keep logging the broken links, so that when someone views the CLI they are able to quickly diagnose the problem and solve it, rather than having to run locally or enable logging with another step.

**Comment by adamisntdead** [comment]
Okay, I published version 1.3.0 with your changes, it will be a few days before I finish this refactor (I am quite busy atm)

Thanks for all of your help, if you would like to get write access just say and I will arrange that!

**Pull request merged**
